# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9274fcac1a982776965e8291ee5983eefd5106360d8e3292c1f3cb328e2ef65c6bf4205d571eda7c44695c6f7b3ae1933c2d9fab8fff194354591d12245fe14d

test:
  secret_key_base: cb34e6523538e5614d89578b209743eba614f2543f96a2a77809334dd254d1467e2e97c1089faf26c82883f3bfb01f91ca94bf38f095360fdeecebe16384061f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
